### ISSUE TITLE
Kein Code

### ISSUE THREAD

**Issue by Interacy** [ggmanugg/energystarnight_bot#1]
Hallo, Ich würde gerne dein Script benutzen, aber ich kann keinen Code finden. Kannst du mir bitte weiterhelfen?

**Comment by Bastiii1233** [comment]
Hallo
Ich nehme an, dass er dies extra gemacht hat, damit man nachfragen muss, dass man den Code bekommt. Ich wollte ebenfalls nachfragen, ob ich den Code haben könnte, wäre sehr dankbar. Vielen Dank!

**Comment by Interacz** [comment]
Achso, ja ich hoffe auch dass ich den Code bekomme, wäre mega geil.

**Comment by SeanDylanGoff** [comment]
https://thebot.energy

**Comment by ggmanugg** [comment]
Hallo zusammen
Sorry für die viel zu späte Antwort. Für mich hat sich der Aufwand, das Script umzuschreiben nicht gelohnt, weshalb ich es nicht fertig gestellt habe.
Für das Energy Air 2019 kommt wieder ein Script online :)
